import { BasicFetchResult, BasicPageParams } from '/@/api/model/baseModel';

export type BisActivityEventParams = {
  id?: string;
  remarks?: string;
  // createBy?: User;
  createDate?: Date;
  updateDate?: Date;
  bisActivityId?: string;
  bisActivityEventStateId?: string;
  name?: string;
  showStart?: Date;
  showEnd?: Date;
  sellStart?: Date;
  sellEnd?: Date;
  checkStart?: Date;
  checkEnd?: Date;
  isLong?: number;
  isOpen?: number;
  isSplit?: number;
  bisChartPhotourl?: string;
  createSeatState?: number;
  isAutoOffline?: number;
  sendMessageStatus?: number;
  isHide?: number;
  seq?: number;
  wpiaoProjectName?: string;
  wpiaoProjectId?: string;
  wpiaoEventName?: string;
  wpiaoEventId?: string;
  wpiaoProjectMsg?: string;
  sourceShowStart?: Date;
  sourceShowEnd?: Date;
  beforeShowStart?: Date;
  beforeShowEnd?: Date;
  isChangeDate?: number;
  updateId?: string;
  updateName?: string;
  isOverdue?: number;
  isAdvanceSale?: number;
  colorValue?: string;
  // bisActivity?: BisActivity;
  // cgiCard?: CgiCard;
  // bisEventPriceList?: List<BisEventPrice>;
  // bisChartSplitList?: List<BisChartSplit>;
};

export type BisActivityEventPageParams = BasicPageParams & BisActivityEventParams;

export interface BisActivityEventItem {
  id: string;
  remarks: string;
  // createBy: User;
  createDate: Date;
  updateDate: Date;
  bisActivityId: string;
  bisActivityEventStateId: string;
  name: string;
  showStart: Date;
  showEnd: Date;
  sellStart: Date;
  sellEnd: Date;
  checkStart: Date;
  checkEnd: Date;
  isLong: number;
  isOpen: number;
  isSplit: number;
  bisChartPhotourl: string;
  createSeatState: number;
  isAutoOffline: number;
  sendMessageStatus: number;
  isHide: number;
  seq: number;
  wpiaoProjectName: string;
  wpiaoProjectId: string;
  wpiaoEventName: string;
  wpiaoEventId: string;
  wpiaoProjectMsg: string;
  sourceShowStart: Date;
  sourceShowEnd: Date;
  beforeShowStart: Date;
  beforeShowEnd: Date;
  isChangeDate: number;
  updateId: string;
  updateName: string;
  isOverdue: number;
  isAdvanceSale: number;
  colorValue: string;
  // bisActivity: BisActivity;
  // cgiCard: CgiCard;
  // bisEventPriceList: List<BisEventPrice>;
  // bisChartSplitList: List<BisChartSplit>;
}

export type BisActivityEventListGetResultModel = BasicFetchResult<BisActivityEventItem>;
