import { BasicFetchResult, BasicPageParams } from '/@/api/model/baseModel';
import { UserBaseInfoVO } from '/@/api/sys/model/userModel';
import { BisActivityEventItem } from '/@/api/bis/model/bisActivityEventModel';
import { ViewPriceItem } from '/@/api/bis/model/viewPriceModel';

export type BisActivityParams = {
  id?: string;
  remarks?: string;
  createBy?: UserBaseInfoVO;
  createDate?: Date;
  updateDate?: Date;
  bisActivityTypeId?: string;
  tmpPlaceId?: string;
  name?: string;
  nameAlias?: string;
  photoVer?: string;
  photoPoster?: string;
  photoHor?: string;
  photoSmall?: string;
  describe?: string;
  isSale?: number;
  isSeat?: number;
  isTest?: number;
  isCheckDelay?: number;
  checkDelayMinute?: number;
  isAppendCheckDelayMsg?: number;
  appendCheckDelayMsg?: string;
  isOfficialNoCheckDelay?: number;
  isNoAgent?: number;
  isNotwxcard?: number;
  seq?: number;
  qyTotag?: string;
  promptOne?: string;
  promptTwo?: string;
  promptThree?: string;
  videoUrl?: string;
  attention?: string;
  bisActivityStateId?: string;
  fatherId?: string;
  businessDiscount?: number;
  businessFixed?: number;
  ext?: string;
  extSystem?: string;
  groupId?: string;
  pftName?: string;
  pftIds?: string;
  tmpPaperId?: string;
  isSnapup?: number;
  isRedisActivity?: number;
  childId?: string;
  isHide?: number;
  sysOfficeId?: string;
  bisUserId?: string;
  // tmpPlace?: TmpPlace;
  // bisActivityType?: Dict;
  // viewPrice?: ViewPrice;
  extInfo?: string;
  checkDelayMsg?: string;
  nameCorrect?: string;
  // bisActivityEventList?: List<BisActivityEvent>;
  // bisClassicPlateAct?: BisClassicPlateAct;
};

export type BisActivityPageParams = BasicPageParams & BisActivityParams;

export interface BisActivityItem {
  id: string;
  remarks: string;
  createBy: UserBaseInfoVO;
  createDate: Date;
  updateDate: Date;
  bisActivityTypeId: string;
  tmpPlaceId: string;
  name: string;
  nameAlias: string;
  photoVer: string;
  photoPoster: string;
  photoHor: string;
  photoSmall: string;
  describe: string;
  isSale: number;
  isSeat: number;
  isTest: number;
  isCheckDelay: number;
  checkDelayMinute: number;
  isAppendCheckDelayMsg: number;
  appendCheckDelayMsg: string;
  isOfficialNoCheckDelay: number;
  isNoAgent: number;
  isNotwxcard: number;
  seq: number;
  qyTotag: string;
  promptOne: string;
  promptTwo: string;
  promptThree: string;
  videoUrl: string;
  attention: string;
  bisActivityStateId: string;
  fatherId: string;
  businessDiscount: number;
  businessFixed: number;
  ext: string;
  extSystem: string;
  groupId: string;
  pftName: string;
  pftIds: string;
  tmpPaperId: string;
  isSnapup: number;
  isRedisActivity: number;
  childId: string;
  isHide: number;
  sysOfficeId: string;
  bisUserId: string;
  // tmpPlace: TmpPlace;
  // bisActivityType: Dict;
  viewPrice: ViewPriceItem;
  extInfo: string;
  checkDelayMsg: string;
  nameCorrect: string;
  bisActivityEventList: BisActivityEventItem[];
  // bisClassicPlateAct: BisClassicPlateAct;
}

export type BisActivityListGetResultModel = BasicFetchResult<BisActivityItem>;
