import { BasicColumn, FormSchema } from '/@/components/Table';
import { useI18n } from '/@/hooks/web/useI18n';

const { t } = useI18n();

const placeholderText = t('common.fuzzySearchText');

export const columns: BasicColumn[] = [
  {
    title: 'ID',
    dataIndex: 'id',
    width: 120,
    defaultHidden: true,
  },
  {
    title: '活动主表ID',
    dataIndex: 'bisActivityId',
    width: 120,
  },
  {
    title: '场次状态ID（颜色标记）',
    dataIndex: 'bisActivityEventStateId',
    width: 120,
  },
  {
    title: '场次名称',
    dataIndex: 'name',
    width: 120,
  },
  {
    title: '演出开始时间',
    dataIndex: 'showStart',
    width: 120,
  },
  {
    title: '演出结束时间',
    dataIndex: 'showEnd',
    width: 120,
  },
  {
    title: '售票时间',
    dataIndex: 'sellStart',
    width: 120,
  },
  {
    title: '停售时间',
    dataIndex: 'sellEnd',
    width: 120,
  },
  {
    title: '检票开始时间',
    dataIndex: 'checkStart',
    width: 120,
  },
  {
    title: '检票结束时间',
    dataIndex: 'checkEnd',
    width: 120,
  },
  {
    title: '是否长期有效',
    dataIndex: 'isLong',
    width: 120,
  },
  {
    title: '是否座位互通',
    dataIndex: 'isOpen',
    width: 120,
  },
  {
    title: '是否多结构',
    dataIndex: 'isSplit',
    width: 120,
  },
  {
    title: '多结构预览图',
    dataIndex: 'bisChartPhotourl',
    width: 120,
  },
  {
    title: '生成座位状态',
    dataIndex: 'createSeatState',
    width: 120,
  },
  {
    title: '是否开启离线自动同步',
    dataIndex: 'isAutoOffline',
    width: 120,
  },
  {
    title: '发送短信状态',
    dataIndex: 'sendMessageStatus',
    width: 120,
  },
  {
    title: '隐藏',
    dataIndex: 'isHide',
    width: 120,
  },
  {
    title: '排序',
    dataIndex: 'seq',
    width: 120,
  },
  {
    title: '微票活动名',
    dataIndex: 'wpiaoProjectName',
    width: 120,
  },
  {
    title: '微票活动id',
    dataIndex: 'wpiaoProjectId',
    width: 120,
  },
  {
    title: '微票场次名',
    dataIndex: 'wpiaoEventName',
    width: 120,
  },
  {
    title: '微票场次ID',
    dataIndex: 'wpiaoEventId',
    width: 120,
  },
  {
    title: '微票活动场次信息',
    dataIndex: 'wpiaoProjectMsg',
    width: 120,
  },
  {
    title: '最初演出开始时间',
    dataIndex: 'sourceShowStart',
    width: 120,
  },
  {
    title: '最初演出结束时间',
    dataIndex: 'sourceShowEnd',
    width: 120,
  },
  {
    title: '更改前演出开始时间',
    dataIndex: 'beforeShowStart',
    width: 120,
  },
  {
    title: '更改前演出结束时间',
    dataIndex: 'beforeShowEnd',
    width: 120,
  },
  {
    title: '是否更改演出时间',
    dataIndex: 'isChangeDate',
    width: 120,
  },
  {
    title: '更新者',
    dataIndex: 'updateId',
    width: 120,
  },
  {
    title: '更新者名称',
    dataIndex: 'updateName',
    width: 120,
  },
  {
    title: '场次是否过期',
    dataIndex: 'isOverdue',
    width: 120,
  },
  {
    title: '场次是否预售',
    dataIndex: 'isAdvanceSale',
    width: 120,
  },
  {
    title: '颜色色值',
    dataIndex: 'colorValue',
    width: 120,
  },
  {
    title: '活动',
    dataIndex: 'bisActivity',
    width: 120,
  },
  {
    title: '卡券',
    dataIndex: 'cgiCard',
    width: 120,
  },
  {
    title: '票价集合',
    dataIndex: 'bisEventPriceList',
    width: 120,
  },
  {
    title: '票图结构集合',
    dataIndex: 'bisChartSplitList',
    width: 120,
  },
];

export const searchFormSchema: FormSchema[] = [
  {
    field: 'bisActivityId',
    label: '活动主表ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisActivityEventStateId',
    label: '场次状态ID（颜色标记）',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'name',
    label: '场次名称',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'showStart',
    label: '演出开始时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'showEnd',
    label: '演出结束时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sellStart',
    label: '售票时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sellEnd',
    label: '停售时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'checkStart',
    label: '检票开始时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'checkEnd',
    label: '检票结束时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isLong',
    label: '是否长期有效',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isOpen',
    label: '是否座位互通',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isSplit',
    label: '是否多结构',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisChartPhotourl',
    label: '多结构预览图',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'createSeatState',
    label: '生成座位状态',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isAutoOffline',
    label: '是否开启离线自动同步',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sendMessageStatus',
    label: '发送短信状态',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isHide',
    label: '隐藏',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'seq',
    label: '排序',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'wpiaoProjectName',
    label: '微票活动名',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'wpiaoProjectId',
    label: '微票活动id',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'wpiaoEventName',
    label: '微票场次名',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'wpiaoEventId',
    label: '微票场次ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'wpiaoProjectMsg',
    label: '微票活动场次信息',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sourceShowStart',
    label: '最初演出开始时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sourceShowEnd',
    label: '最初演出结束时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'beforeShowStart',
    label: '更改前演出开始时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'beforeShowEnd',
    label: '更改前演出结束时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isChangeDate',
    label: '是否更改演出时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'updateId',
    label: '更新者',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'updateName',
    label: '更新者名称',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isOverdue',
    label: '场次是否过期',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isAdvanceSale',
    label: '场次是否预售',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'colorValue',
    label: '颜色色值',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisActivity',
    label: '活动',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'cgiCard',
    label: '卡券',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisEventPriceList',
    label: '票价集合',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisChartSplitList',
    label: '票图结构集合',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
];

export const formSchema: FormSchema[] = [
  {
    field: 'bisActivityId',
    label: '活动主表ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisActivityEventStateId',
    label: '场次状态ID（颜色标记）',
    required: false,
    component: 'Input',
  },
  {
    field: 'name',
    label: '场次名称',
    required: false,
    component: 'Input',
  },
  {
    field: 'showStart',
    label: '演出开始时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'showEnd',
    label: '演出结束时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'sellStart',
    label: '售票时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'sellEnd',
    label: '停售时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'checkStart',
    label: '检票开始时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'checkEnd',
    label: '检票结束时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'isLong',
    label: '是否长期有效',
    required: false,
    component: 'Input',
  },
  {
    field: 'isOpen',
    label: '是否座位互通',
    required: false,
    component: 'Input',
  },
  {
    field: 'isSplit',
    label: '是否多结构',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisChartPhotourl',
    label: '多结构预览图',
    required: false,
    component: 'Input',
  },
  {
    field: 'createSeatState',
    label: '生成座位状态',
    required: false,
    component: 'Input',
  },
  {
    field: 'isAutoOffline',
    label: '是否开启离线自动同步',
    required: false,
    component: 'Input',
  },
  {
    field: 'sendMessageStatus',
    label: '发送短信状态',
    required: false,
    component: 'Input',
  },
  {
    field: 'isHide',
    label: '隐藏',
    required: false,
    component: 'Input',
  },
  {
    field: 'seq',
    label: '排序',
    required: false,
    component: 'Input',
  },
  {
    field: 'wpiaoProjectName',
    label: '微票活动名',
    required: false,
    component: 'Input',
  },
  {
    field: 'wpiaoProjectId',
    label: '微票活动id',
    required: false,
    component: 'Input',
  },
  {
    field: 'wpiaoEventName',
    label: '微票场次名',
    required: false,
    component: 'Input',
  },
  {
    field: 'wpiaoEventId',
    label: '微票场次ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'wpiaoProjectMsg',
    label: '微票活动场次信息',
    required: false,
    component: 'Input',
  },
  {
    field: 'sourceShowStart',
    label: '最初演出开始时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'sourceShowEnd',
    label: '最初演出结束时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'beforeShowStart',
    label: '更改前演出开始时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'beforeShowEnd',
    label: '更改前演出结束时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'isChangeDate',
    label: '是否更改演出时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'updateId',
    label: '更新者',
    required: false,
    component: 'Input',
  },
  {
    field: 'updateName',
    label: '更新者名称',
    required: false,
    component: 'Input',
  },
  {
    field: 'isOverdue',
    label: '场次是否过期',
    required: false,
    component: 'Input',
  },
  {
    field: 'isAdvanceSale',
    label: '场次是否预售',
    required: false,
    component: 'Input',
  },
  {
    field: 'colorValue',
    label: '颜色色值',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisActivity',
    label: '活动',
    required: false,
    component: 'Input',
  },
  {
    field: 'cgiCard',
    label: '卡券',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisEventPriceList',
    label: '票价集合',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisChartSplitList',
    label: '票图结构集合',
    required: false,
    component: 'Input',
  },
];
