import { BasicFetchResult, BasicPageParams } from '/@/api/model/baseModel';

export type OfficeParams = {
  id?: string;
  remarks?: string;
  // createBy?: User;
  createDate?: Date;
  updateDate?: Date;
  parent?: OfficeItem;
  parentIds?: string;
  name?: string;
  // area?: Area;
  code?: string;
  type?: string;
  grade?: string;
  address?: string;
  zipCode?: string;
  master?: string;
  phone?: string;
  fax?: string;
  email?: string;
  useable?: string;
  damaiUserName?: string;
  zhiyoubaoUserName?: string;
  zhiyoubaoCorpCode?: string;
  zhiyoubaoPrivateKey?: string;
  piaofutongUserName?: string;
  piaofutongPassword?: string;
  weipiaoUserName?: string;
  weipiaoPassword?: string;
  maizuoUserName?: string;
  maizuoPassword?: string;
  baoliUserName?: string;
  baoliPassword?: string;
  zhongyanUserName?: string;
  zhongyanPassword?: string;
  jqiclubSupplierIdentity?: string;
  jqiclubSignkey?: string;
  wpiaoUserName?: string;
  pftmxUserName?: string;
  pftmxKey?: string;
  maoyanUserName?: string;
  accOpenid?: string;
  accName?: string;
  sysWxConfigId?: string;
  maizuoNewLockType?: string;
  businessUserId?: string;
  businessAgentId?: string;
  isClassicShop?: string;
  merchantType?: string;
  companyName?: string;
  provCode?: string;
  areaCode?: string;
  socialCreditCode?: string;
  socialCreditCodeExpires?: string;
  businessScope?: string;
  legalPerson?: string;
  legalCertId?: string;
  legalCertIdExpires?: string;
  legalMp?: string;
  companyAddress?: string;
  bankCode?: string;
  cardNo?: string;
  cardName?: string;
  certId?: string;
  telNo?: string;
  settleAccountId?: string;
  settleAccountStatus?: string;
  adaMsg?: string;
  payFile?: string;
  adaMemberId?: string;
  adaInfoId?: string;
  settlementRatio?: string;
};

export type OfficePageParams = BasicPageParams & OfficeParams;

export interface OfficeItem {
  id: string;
  remarks: string;
  // createBy: User;
  createDate: Date;
  updateDate: Date;
  parent: OfficeItem;
  parentIds: string;
  name: string;
  // area: Area;
  code: string;
  type: string;
  grade: string;
  address: string;
  zipCode: string;
  master: string;
  phone: string;
  fax: string;
  email: string;
  useable: string;
  damaiUserName: string;
  zhiyoubaoUserName: string;
  zhiyoubaoCorpCode: string;
  zhiyoubaoPrivateKey: string;
  piaofutongUserName: string;
  piaofutongPassword: string;
  weipiaoUserName: string;
  weipiaoPassword: string;
  maizuoUserName: string;
  maizuoPassword: string;
  baoliUserName: string;
  baoliPassword: string;
  zhongyanUserName: string;
  zhongyanPassword: string;
  jqiclubSupplierIdentity: string;
  jqiclubSignkey: string;
  wpiaoUserName: string;
  pftmxUserName: string;
  pftmxKey: string;
  maoyanUserName: string;
  accOpenid: string;
  accName: string;
  sysWxConfigId: string;
  maizuoNewLockType: string;
  businessUserId: string;
  businessAgentId: string;
  isClassicShop: string;
  merchantType: string;
  companyName: string;
  provCode: string;
  areaCode: string;
  socialCreditCode: string;
  socialCreditCodeExpires: string;
  businessScope: string;
  legalPerson: string;
  legalCertId: string;
  legalCertIdExpires: string;
  legalMp: string;
  companyAddress: string;
  bankCode: string;
  cardNo: string;
  cardName: string;
  certId: string;
  telNo: string;
  settleAccountId: string;
  settleAccountStatus: string;
  adaMsg: string;
  payFile: string;
  adaMemberId: string;
  adaInfoId: string;
  settlementRatio: string;
}

export type OfficeListGetResultModel = BasicFetchResult<OfficeItem>;
