import { BasicColumn, FormSchema } from '/@/components/Table';
import { useI18n } from '/@/hooks/web/useI18n';

const { t } = useI18n();

const placeholderText = t('common.fuzzySearchText');

export const columns: BasicColumn[] = [
  {
    title: 'ID',
    dataIndex: 'id',
    width: 120,
    defaultHidden: true,
  },
  {
    title: '活动名称',
    dataIndex: 'name',
    width: 120,
  },
  {
    title: '活动别名',
    dataIndex: 'nameAlias',
    width: 120,
  },
  {
    title: '商户名称',
    dataIndex: ['createBy', 'companyName'],
    width: 120,
  },
  {
    title: '活动时间',
    dataIndex: ['viewPrice', 'showStart'],
    width: 120,
    format: (text, record) => {
      if (record.isHide > 0) return '长期有效';
      return text || '-';
    },
  },
  {
    title: '票价',
    dataIndex: ['viewPrice', 'showPrice'],
    width: 120,
    format: (text) => {
      return text ? '￥' + text : '-';
    },
  },
  {
    title: '活动状态',
    dataIndex: 'status',
  },
  {
    title: '通知',
    dataIndex: 'qyTotag',
    width: 120,
  },
  {
    title: '活动分类',
    dataIndex: ['bisActivityType', 'label'],
    width: 120,
  },
  {
    title: '活动排序',
    dataIndex: 'seq',
    width: 120,
  },
  {
    title: '修改时间',
    dataIndex: 'updateDate',
    align: 'center',
    defaultHidden: true,
    width: 120,
  },
  {
    title: '创建时间',
    dataIndex: 'createDate',
    align: 'center',
    defaultHidden: true,
    width: 120,
  },
  {
    title: '销售状态',
    dataIndex: 'isSale',
    width: 120,
  },
  {
    title: '备注',
    dataIndex: 'remarks',
    width: 120,
  },
];

export const searchFormSchema: FormSchema[] = [
  {
    field: 'bisActivityTypeId',
    label: '活动类型ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'tmpPlaceId',
    label: '活动门店ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'name',
    label: '活动名称',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'nameAlias',
    label: '活动别名',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'photoVer',
    label: '封面图片竖版',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'photoPoster',
    label: '海报模板',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'photoHor',
    label: '封面图片横版',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'photoSmall',
    label: '封面图片小',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'describe',
    label: '活动介绍',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isSale',
    label: '是否上架',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isSeat',
    label: '是否选座',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isTest',
    label: '是否测试',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isCheckDelay',
    label: '是否延迟检票',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'checkDelayMinute',
    label: '检票延迟时间',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isAppendCheckDelayMsg',
    label: '是否追加延迟检票提示',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'appendCheckDelayMsg',
    label: '追加延迟检票提示',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isOfficialNoCheckDelay',
    label: '官方店铺不延迟',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isNoAgent',
    label: '禁止分销',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isNotwxcard',
    label: '是否非电子',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'seq',
    label: '排序',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'qyTotag',
    label: '企业通知标签',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'promptOne',
    label: '提示语1|活动打包到二维码里',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'promptTwo',
    label: '提示语2|黑名单（例外的代理商的user_id）',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'promptThree',
    label: '提示语3|白名单（例外的代理商的user_id）',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'videoUrl',
    label: '视频链接(暂时用作讯飞链接)',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'attention',
    label: '购票须知(用作讯飞预计存储内容字段)',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisActivityStateId',
    label: '活动验证方式(wx_card,ele_card,ems,take_code,name_phone,ticket_lib_third)',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'fatherId',
    label: '关联ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'businessDiscount',
    label: '商户代理商户折扣',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'businessFixed',
    label: '商户代理商户固定金额',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'ext',
    label: '扩展长字段说明',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'extSystem',
    label: '神秘代码',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'groupId',
    label: '组ID,判断哪些活动属于一组,用户自互通座位状态，（好像没用上）',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'pftName',
    label: '票付通产品名称',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'pftIds',
    label: '票付通ID: lid_aid',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'tmpPaperId',
    label: '票纸票面定义',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isSnapup',
    label: '是否抢票活动',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isRedisActivity',
    label: '是否REDIS活动',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'childId',
    label: '关联ID',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'isHide',
    label: '代理隐藏',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'sysOfficeId',
    label: '主办方',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisUserId',
    label: '代理商用户',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'tmpPlace',
    label: '地址',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisActivityType',
    label: '活动分类',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'viewPrice',
    label: '票价显示',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'extInfo',
    label: '扩展长字段翻译说明',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'checkDelayMsg',
    label: '转换后的延迟检票提示',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'nameCorrect',
    label: '活动名对齐',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisActivityEventList',
    label: 'bisActivityEventList',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
  {
    field: 'bisClassicPlateAct',
    label: 'bisClassicPlateAct',
    component: 'Input',
    componentProps: { placeholder: placeholderText },
  },
];

export const formSchema: FormSchema[] = [
  {
    field: 'bisActivityTypeId',
    label: '活动类型ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'tmpPlaceId',
    label: '活动门店ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'name',
    label: '活动名称',
    required: false,
    component: 'Input',
  },
  {
    field: 'nameAlias',
    label: '活动别名',
    required: false,
    component: 'Input',
  },
  {
    field: 'photoVer',
    label: '封面图片竖版',
    required: false,
    component: 'Input',
  },
  {
    field: 'photoPoster',
    label: '海报模板',
    required: false,
    component: 'Input',
  },
  {
    field: 'photoHor',
    label: '封面图片横版',
    required: false,
    component: 'Input',
  },
  {
    field: 'photoSmall',
    label: '封面图片小',
    required: false,
    component: 'Input',
  },
  {
    field: 'describe',
    label: '活动介绍',
    required: false,
    component: 'Input',
  },
  {
    field: 'isSale',
    label: '是否上架',
    required: false,
    component: 'Input',
  },
  {
    field: 'isSeat',
    label: '是否选座',
    required: false,
    component: 'Input',
  },
  {
    field: 'isTest',
    label: '是否测试',
    required: false,
    component: 'Input',
  },
  {
    field: 'isCheckDelay',
    label: '是否延迟检票',
    required: false,
    component: 'Input',
  },
  {
    field: 'checkDelayMinute',
    label: '检票延迟时间',
    required: false,
    component: 'Input',
  },
  {
    field: 'isAppendCheckDelayMsg',
    label: '是否追加延迟检票提示',
    required: false,
    component: 'Input',
  },
  {
    field: 'appendCheckDelayMsg',
    label: '追加延迟检票提示',
    required: false,
    component: 'Input',
  },
  {
    field: 'isOfficialNoCheckDelay',
    label: '官方店铺不延迟',
    required: false,
    component: 'Input',
  },
  {
    field: 'isNoAgent',
    label: '禁止分销',
    required: false,
    component: 'Input',
  },
  {
    field: 'isNotwxcard',
    label: '是否非电子',
    required: false,
    component: 'Input',
  },
  {
    field: 'seq',
    label: '排序',
    required: false,
    component: 'Input',
  },
  {
    field: 'qyTotag',
    label: '企业通知标签',
    required: false,
    component: 'Input',
  },
  {
    field: 'promptOne',
    label: '提示语1|活动打包到二维码里',
    required: false,
    component: 'Input',
  },
  {
    field: 'promptTwo',
    label: '提示语2|黑名单（例外的代理商的user_id）',
    required: false,
    component: 'Input',
  },
  {
    field: 'promptThree',
    label: '提示语3|白名单（例外的代理商的user_id）',
    required: false,
    component: 'Input',
  },
  {
    field: 'videoUrl',
    label: '视频链接(暂时用作讯飞链接)',
    required: false,
    component: 'Input',
  },
  {
    field: 'attention',
    label: '购票须知(用作讯飞预计存储内容字段)',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisActivityStateId',
    label: '活动验证方式(wx_card,ele_card,ems,take_code,name_phone,ticket_lib_third)',
    required: false,
    component: 'Input',
  },
  {
    field: 'fatherId',
    label: '关联ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'businessDiscount',
    label: '商户代理商户折扣',
    required: false,
    component: 'Input',
  },
  {
    field: 'businessFixed',
    label: '商户代理商户固定金额',
    required: false,
    component: 'Input',
  },
  {
    field: 'ext',
    label: '扩展长字段说明',
    required: false,
    component: 'Input',
  },
  {
    field: 'extSystem',
    label: '神秘代码',
    required: false,
    component: 'Input',
  },
  {
    field: 'groupId',
    label: '组ID,判断哪些活动属于一组,用户自互通座位状态，（好像没用上）',
    required: false,
    component: 'Input',
  },
  {
    field: 'pftName',
    label: '票付通产品名称',
    required: false,
    component: 'Input',
  },
  {
    field: 'pftIds',
    label: '票付通ID: lid_aid',
    required: false,
    component: 'Input',
  },
  {
    field: 'tmpPaperId',
    label: '票纸票面定义',
    required: false,
    component: 'Input',
  },
  {
    field: 'isSnapup',
    label: '是否抢票活动',
    required: false,
    component: 'Input',
  },
  {
    field: 'isRedisActivity',
    label: '是否REDIS活动',
    required: false,
    component: 'Input',
  },
  {
    field: 'childId',
    label: '关联ID',
    required: false,
    component: 'Input',
  },
  {
    field: 'isHide',
    label: '代理隐藏',
    required: false,
    component: 'Input',
  },
  {
    field: 'sysOfficeId',
    label: '主办方',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisUserId',
    label: '代理商用户',
    required: false,
    component: 'Input',
  },
  {
    field: 'tmpPlace',
    label: '地址',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisActivityType',
    label: '活动分类',
    required: false,
    component: 'Input',
  },
  {
    field: 'viewPrice',
    label: '票价显示',
    required: false,
    component: 'Input',
  },
  {
    field: 'extInfo',
    label: '扩展长字段翻译说明',
    required: false,
    component: 'Input',
  },
  {
    field: 'checkDelayMsg',
    label: '转换后的延迟检票提示',
    required: false,
    component: 'Input',
  },
  {
    field: 'nameCorrect',
    label: '活动名对齐',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisActivityEventList',
    label: 'bisActivityEventList',
    required: false,
    component: 'Input',
  },
  {
    field: 'bisClassicPlateAct',
    label: 'bisClassicPlateAct',
    required: false,
    component: 'Input',
  },
];
